// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// mvrnormArma
arma::mat mvrnormArma(int n, const arma::vec& mu, const arma::mat& sigma);
RcppExport SEXP _BinHEP_mvrnormArma(SEXP nSEXP, SEXP muSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(mvrnormArma(n, mu, sigma));
    return rcpp_result_gen;
END_RCPP
}
// mvrnormArma1
arma::colvec mvrnormArma1(const arma::vec& mu, const arma::mat& sigma);
RcppExport SEXP _BinHEP_mvrnormArma1(SEXP muSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(mvrnormArma1(mu, sigma));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_qtnorm_vec
arma::vec rcpp_qtnorm_vec(const arma::vec& p, const arma::vec& mu, const arma::vec& a, const arma::vec& b);
RcppExport SEXP _BinHEP_rcpp_qtnorm_vec(SEXP pSEXP, SEXP muSEXP, SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type p(pSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_qtnorm_vec(p, mu, a, b));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_rtnorm_vec
arma::vec rcpp_rtnorm_vec(const arma::vec& mu, const arma::vec& a, const arma::vec& b);
RcppExport SEXP _BinHEP_rcpp_rtnorm_vec(SEXP muSEXP, SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_rtnorm_vec(mu, a, b));
    return rcpp_result_gen;
END_RCPP
}
// cpp_rdirichletArma1
arma::vec cpp_rdirichletArma1(const arma::colvec& parameters);
RcppExport SEXP _BinHEP_cpp_rdirichletArma1(SEXP parametersSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type parameters(parametersSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_rdirichletArma1(parameters));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_sample
arma::uvec rcpp_sample(const arma::uvec vec, const int size, const arma::colvec prob);
RcppExport SEXP _BinHEP_rcpp_sample(SEXP vecSEXP, SEXP sizeSEXP, SEXP probSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::uvec >::type vec(vecSEXP);
    Rcpp::traits::input_parameter< const int >::type size(sizeSEXP);
    Rcpp::traits::input_parameter< const arma::colvec >::type prob(probSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_sample(vec, size, prob));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_rTheta_conditioned_RaoBlackwellAuxSMC
arma::mat rcpp_rTheta_conditioned_RaoBlackwellAuxSMC(const Rcpp::IntegerVector& y, const arma::colvec& delta, const arma::colvec& x, const arma::mat& matFF, const arma::colvec& mu0, const arma::mat& Sigma0, const arma::mat& G, const arma::mat& G_star, const arma::mat& SigmaEps, const arma::mat& SigmaEps_star, const Rcpp::IntegerVector& Tstar, const int nSim);
RcppExport SEXP _BinHEP_rcpp_rTheta_conditioned_RaoBlackwellAuxSMC(SEXP ySEXP, SEXP deltaSEXP, SEXP xSEXP, SEXP matFFSEXP, SEXP mu0SEXP, SEXP Sigma0SEXP, SEXP GSEXP, SEXP G_starSEXP, SEXP SigmaEpsSEXP, SEXP SigmaEps_starSEXP, SEXP TstarSEXP, SEXP nSimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type matFF(matFFSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type mu0(mu0SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Sigma0(Sigma0SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type G(GSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type G_star(G_starSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type SigmaEps(SigmaEpsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type SigmaEps_star(SigmaEps_starSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type Tstar(TstarSEXP);
    Rcpp::traits::input_parameter< const int >::type nSim(nSimSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_rTheta_conditioned_RaoBlackwellAuxSMC(y, delta, x, matFF, mu0, Sigma0, G, G_star, SigmaEps, SigmaEps_star, Tstar, nSim));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_rEta_conditioned_RaoBlackwellAuxSMC
arma::vec rcpp_rEta_conditioned_RaoBlackwellAuxSMC(const Rcpp::IntegerVector& y, const arma::colvec& delta, const arma::colvec& x, const arma::mat& matFF, const arma::colvec& mu0, const arma::mat& Sigma0, const arma::mat& G, const arma::mat& G_star, const arma::mat& SigmaEps, const arma::mat& SigmaEps_star, const Rcpp::IntegerVector& Tstar, const int nSim);
RcppExport SEXP _BinHEP_rcpp_rEta_conditioned_RaoBlackwellAuxSMC(SEXP ySEXP, SEXP deltaSEXP, SEXP xSEXP, SEXP matFFSEXP, SEXP mu0SEXP, SEXP Sigma0SEXP, SEXP GSEXP, SEXP G_starSEXP, SEXP SigmaEpsSEXP, SEXP SigmaEps_starSEXP, SEXP TstarSEXP, SEXP nSimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type matFF(matFFSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type mu0(mu0SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Sigma0(Sigma0SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type G(GSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type G_star(G_starSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type SigmaEps(SigmaEpsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type SigmaEps_star(SigmaEps_starSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type Tstar(TstarSEXP);
    Rcpp::traits::input_parameter< const int >::type nSim(nSimSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_rEta_conditioned_RaoBlackwellAuxSMC(y, delta, x, matFF, mu0, Sigma0, G, G_star, SigmaEps, SigmaEps_star, Tstar, nSim));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_get_Ri_wSplit
int rcpp_get_Ri_wSplit(const arma::mat& theta, const arma::mat& Zi, const arma::vec& Tstar);
RcppExport SEXP _BinHEP_rcpp_get_Ri_wSplit(SEXP thetaSEXP, SEXP ZiSEXP, SEXP TstarSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Zi(ZiSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Tstar(TstarSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_get_Ri_wSplit(theta, Zi, Tstar));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_get_Ri_wSplit_from_eta
int rcpp_get_Ri_wSplit_from_eta(const arma::vec eta, const arma::vec Tstar);
RcppExport SEXP _BinHEP_rcpp_get_Ri_wSplit_from_eta(SEXP etaSEXP, SEXP TstarSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type Tstar(TstarSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_get_Ri_wSplit_from_eta(eta, Tstar));
    return rcpp_result_gen;
END_RCPP
}
// sample_Ri_under_g_wSplit
arma::vec sample_Ri_under_g_wSplit(const int TT, const arma::mat& matFF, const arma::colvec& mu0, const arma::mat& Sigma0, const arma::mat& G, const arma::mat& G_star, const arma::mat& SigmaEps, const arma::mat& SigmaEps_star, const arma::vec& Tstar, const int nSim);
RcppExport SEXP _BinHEP_sample_Ri_under_g_wSplit(SEXP TTSEXP, SEXP matFFSEXP, SEXP mu0SEXP, SEXP Sigma0SEXP, SEXP GSEXP, SEXP G_starSEXP, SEXP SigmaEpsSEXP, SEXP SigmaEps_starSEXP, SEXP TstarSEXP, SEXP nSimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type TT(TTSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type matFF(matFFSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type mu0(mu0SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Sigma0(Sigma0SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type G(GSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type G_star(G_starSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type SigmaEps(SigmaEpsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type SigmaEps_star(SigmaEps_starSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Tstar(TstarSEXP);
    Rcpp::traits::input_parameter< const int >::type nSim(nSimSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_Ri_under_g_wSplit(TT, matFF, mu0, Sigma0, G, G_star, SigmaEps, SigmaEps_star, Tstar, nSim));
    return rcpp_result_gen;
END_RCPP
}
// sample_biniary_ts_wSplit_from_G
arma::ivec sample_biniary_ts_wSplit_from_G(const double mu, const int TT, const arma::mat& matFF, const arma::colvec& mu0, const arma::mat& Sigma0, const arma::mat& G, const arma::mat& G_star, const arma::mat& SigmaEps, const arma::mat& SigmaEps_star, const arma::vec& Tstar);
RcppExport SEXP _BinHEP_sample_biniary_ts_wSplit_from_G(SEXP muSEXP, SEXP TTSEXP, SEXP matFFSEXP, SEXP mu0SEXP, SEXP Sigma0SEXP, SEXP GSEXP, SEXP G_starSEXP, SEXP SigmaEpsSEXP, SEXP SigmaEps_starSEXP, SEXP TstarSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const int >::type TT(TTSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type matFF(matFFSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type mu0(mu0SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Sigma0(Sigma0SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type G(GSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type G_star(G_starSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type SigmaEps(SigmaEpsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type SigmaEps_star(SigmaEps_starSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Tstar(TstarSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_biniary_ts_wSplit_from_G(mu, TT, matFF, mu0, Sigma0, G, G_star, SigmaEps, SigmaEps_star, Tstar));
    return rcpp_result_gen;
END_RCPP
}
// SUN_gibbs_collapsed_sampler_v2
Rcpp::List SUN_gibbs_collapsed_sampler_v2(const Rcpp::List data, const arma::mat X, const Rcpp::CharacterVector IDs, Rcpp::List STATE, const Rcpp::List Prior, const Rcpp::List gPrior, const int sample, const int thinning, const int burn, const int nSim);
RcppExport SEXP _BinHEP_SUN_gibbs_collapsed_sampler_v2(SEXP dataSEXP, SEXP XSEXP, SEXP IDsSEXP, SEXP STATESEXP, SEXP PriorSEXP, SEXP gPriorSEXP, SEXP sampleSEXP, SEXP thinningSEXP, SEXP burnSEXP, SEXP nSimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector >::type IDs(IDsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type STATE(STATESEXP);
    Rcpp::traits::input_parameter< const Rcpp::List >::type Prior(PriorSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List >::type gPrior(gPriorSEXP);
    Rcpp::traits::input_parameter< const int >::type sample(sampleSEXP);
    Rcpp::traits::input_parameter< const int >::type thinning(thinningSEXP);
    Rcpp::traits::input_parameter< const int >::type burn(burnSEXP);
    Rcpp::traits::input_parameter< const int >::type nSim(nSimSEXP);
    rcpp_result_gen = Rcpp::wrap(SUN_gibbs_collapsed_sampler_v2(data, X, IDs, STATE, Prior, gPrior, sample, thinning, burn, nSim));
    return rcpp_result_gen;
END_RCPP
}
// SUN_gibbs_collapsed_sampler_v2_Store_Ri_and_delta
Rcpp::List SUN_gibbs_collapsed_sampler_v2_Store_Ri_and_delta(const Rcpp::List data, const arma::mat X, const Rcpp::CharacterVector IDs, Rcpp::List STATE, const Rcpp::List Prior, const Rcpp::List gPrior, const int sample, const int thinning, const int burn, const int nSim);
RcppExport SEXP _BinHEP_SUN_gibbs_collapsed_sampler_v2_Store_Ri_and_delta(SEXP dataSEXP, SEXP XSEXP, SEXP IDsSEXP, SEXP STATESEXP, SEXP PriorSEXP, SEXP gPriorSEXP, SEXP sampleSEXP, SEXP thinningSEXP, SEXP burnSEXP, SEXP nSimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector >::type IDs(IDsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type STATE(STATESEXP);
    Rcpp::traits::input_parameter< const Rcpp::List >::type Prior(PriorSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List >::type gPrior(gPriorSEXP);
    Rcpp::traits::input_parameter< const int >::type sample(sampleSEXP);
    Rcpp::traits::input_parameter< const int >::type thinning(thinningSEXP);
    Rcpp::traits::input_parameter< const int >::type burn(burnSEXP);
    Rcpp::traits::input_parameter< const int >::type nSim(nSimSEXP);
    rcpp_result_gen = Rcpp::wrap(SUN_gibbs_collapsed_sampler_v2_Store_Ri_and_delta(data, X, IDs, STATE, Prior, gPrior, sample, thinning, burn, nSim));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_get_Ri_wSplit_v3
int rcpp_get_Ri_wSplit_v3(const arma::mat& theta, const arma::mat& Zi, const arma::vec& Tstar);
RcppExport SEXP _BinHEP_rcpp_get_Ri_wSplit_v3(SEXP thetaSEXP, SEXP ZiSEXP, SEXP TstarSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Zi(ZiSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Tstar(TstarSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_get_Ri_wSplit_v3(theta, Zi, Tstar));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_get_Ri_wSplit_from_eta_v3
int rcpp_get_Ri_wSplit_from_eta_v3(const arma::vec eta, const arma::vec Tstar);
RcppExport SEXP _BinHEP_rcpp_get_Ri_wSplit_from_eta_v3(SEXP etaSEXP, SEXP TstarSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type Tstar(TstarSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_get_Ri_wSplit_from_eta_v3(eta, Tstar));
    return rcpp_result_gen;
END_RCPP
}
// sample_Ri_under_g_wSplit_v3
arma::vec sample_Ri_under_g_wSplit_v3(const int TT, const arma::mat& matFF, const arma::colvec& mu0, const arma::mat& Sigma0, const arma::mat& G, const arma::mat& G_star, const arma::mat& SigmaEps, const arma::mat& SigmaEps_star, const arma::vec& Tstar, const int nSim);
RcppExport SEXP _BinHEP_sample_Ri_under_g_wSplit_v3(SEXP TTSEXP, SEXP matFFSEXP, SEXP mu0SEXP, SEXP Sigma0SEXP, SEXP GSEXP, SEXP G_starSEXP, SEXP SigmaEpsSEXP, SEXP SigmaEps_starSEXP, SEXP TstarSEXP, SEXP nSimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type TT(TTSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type matFF(matFFSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type mu0(mu0SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Sigma0(Sigma0SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type G(GSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type G_star(G_starSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type SigmaEps(SigmaEpsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type SigmaEps_star(SigmaEps_starSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Tstar(TstarSEXP);
    Rcpp::traits::input_parameter< const int >::type nSim(nSimSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_Ri_under_g_wSplit_v3(TT, matFF, mu0, Sigma0, G, G_star, SigmaEps, SigmaEps_star, Tstar, nSim));
    return rcpp_result_gen;
END_RCPP
}
// SUN_gibbs_collapsed_sampler_v3
Rcpp::List SUN_gibbs_collapsed_sampler_v3(const Rcpp::List data, const arma::mat X, const Rcpp::CharacterVector IDs, Rcpp::List STATE, const Rcpp::List Prior, const Rcpp::List gPrior, const int sample, const int thinning, const int burn, const int nSim);
RcppExport SEXP _BinHEP_SUN_gibbs_collapsed_sampler_v3(SEXP dataSEXP, SEXP XSEXP, SEXP IDsSEXP, SEXP STATESEXP, SEXP PriorSEXP, SEXP gPriorSEXP, SEXP sampleSEXP, SEXP thinningSEXP, SEXP burnSEXP, SEXP nSimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector >::type IDs(IDsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type STATE(STATESEXP);
    Rcpp::traits::input_parameter< const Rcpp::List >::type Prior(PriorSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List >::type gPrior(gPriorSEXP);
    Rcpp::traits::input_parameter< const int >::type sample(sampleSEXP);
    Rcpp::traits::input_parameter< const int >::type thinning(thinningSEXP);
    Rcpp::traits::input_parameter< const int >::type burn(burnSEXP);
    Rcpp::traits::input_parameter< const int >::type nSim(nSimSEXP);
    rcpp_result_gen = Rcpp::wrap(SUN_gibbs_collapsed_sampler_v3(data, X, IDs, STATE, Prior, gPrior, sample, thinning, burn, nSim));
    return rcpp_result_gen;
END_RCPP
}
// SUN_gibbs_collapsed_sampler_v2_Store_Ri_and_delta_v3
Rcpp::List SUN_gibbs_collapsed_sampler_v2_Store_Ri_and_delta_v3(const Rcpp::List data, const arma::mat X, const Rcpp::CharacterVector IDs, Rcpp::List STATE, const Rcpp::List Prior, const Rcpp::List gPrior, const int sample, const int thinning, const int burn, const int nSim);
RcppExport SEXP _BinHEP_SUN_gibbs_collapsed_sampler_v2_Store_Ri_and_delta_v3(SEXP dataSEXP, SEXP XSEXP, SEXP IDsSEXP, SEXP STATESEXP, SEXP PriorSEXP, SEXP gPriorSEXP, SEXP sampleSEXP, SEXP thinningSEXP, SEXP burnSEXP, SEXP nSimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector >::type IDs(IDsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type STATE(STATESEXP);
    Rcpp::traits::input_parameter< const Rcpp::List >::type Prior(PriorSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List >::type gPrior(gPriorSEXP);
    Rcpp::traits::input_parameter< const int >::type sample(sampleSEXP);
    Rcpp::traits::input_parameter< const int >::type thinning(thinningSEXP);
    Rcpp::traits::input_parameter< const int >::type burn(burnSEXP);
    Rcpp::traits::input_parameter< const int >::type nSim(nSimSEXP);
    rcpp_result_gen = Rcpp::wrap(SUN_gibbs_collapsed_sampler_v2_Store_Ri_and_delta_v3(data, X, IDs, STATE, Prior, gPrior, sample, thinning, burn, nSim));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_get_Ri_wSplit_v4
int rcpp_get_Ri_wSplit_v4(const arma::mat& theta, const arma::mat& Zi, const arma::vec& Tstar);
RcppExport SEXP _BinHEP_rcpp_get_Ri_wSplit_v4(SEXP thetaSEXP, SEXP ZiSEXP, SEXP TstarSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Zi(ZiSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Tstar(TstarSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_get_Ri_wSplit_v4(theta, Zi, Tstar));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_get_Ri_wSplit_from_eta_v4
int rcpp_get_Ri_wSplit_from_eta_v4(const arma::vec eta, const arma::vec Tstar);
RcppExport SEXP _BinHEP_rcpp_get_Ri_wSplit_from_eta_v4(SEXP etaSEXP, SEXP TstarSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type Tstar(TstarSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_get_Ri_wSplit_from_eta_v4(eta, Tstar));
    return rcpp_result_gen;
END_RCPP
}
// sample_Ri_under_g_wSplit_v4
arma::vec sample_Ri_under_g_wSplit_v4(const int TT, const arma::mat& matFF, const arma::colvec& mu0, const arma::mat& Sigma0, const arma::mat& G, const arma::mat& G_star, const arma::mat& SigmaEps, const arma::mat& SigmaEps_star, const arma::vec& Tstar, const int nSim);
RcppExport SEXP _BinHEP_sample_Ri_under_g_wSplit_v4(SEXP TTSEXP, SEXP matFFSEXP, SEXP mu0SEXP, SEXP Sigma0SEXP, SEXP GSEXP, SEXP G_starSEXP, SEXP SigmaEpsSEXP, SEXP SigmaEps_starSEXP, SEXP TstarSEXP, SEXP nSimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type TT(TTSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type matFF(matFFSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type mu0(mu0SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Sigma0(Sigma0SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type G(GSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type G_star(G_starSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type SigmaEps(SigmaEpsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type SigmaEps_star(SigmaEps_starSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Tstar(TstarSEXP);
    Rcpp::traits::input_parameter< const int >::type nSim(nSimSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_Ri_under_g_wSplit_v4(TT, matFF, mu0, Sigma0, G, G_star, SigmaEps, SigmaEps_star, Tstar, nSim));
    return rcpp_result_gen;
END_RCPP
}
// SUN_gibbs_collapsed_sampler_v4
Rcpp::List SUN_gibbs_collapsed_sampler_v4(const Rcpp::List data, const arma::mat X, const Rcpp::CharacterVector IDs, Rcpp::List STATE, const Rcpp::List Prior, const Rcpp::List gPrior, const int sample, const int thinning, const int burn, const int nSim);
RcppExport SEXP _BinHEP_SUN_gibbs_collapsed_sampler_v4(SEXP dataSEXP, SEXP XSEXP, SEXP IDsSEXP, SEXP STATESEXP, SEXP PriorSEXP, SEXP gPriorSEXP, SEXP sampleSEXP, SEXP thinningSEXP, SEXP burnSEXP, SEXP nSimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector >::type IDs(IDsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type STATE(STATESEXP);
    Rcpp::traits::input_parameter< const Rcpp::List >::type Prior(PriorSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List >::type gPrior(gPriorSEXP);
    Rcpp::traits::input_parameter< const int >::type sample(sampleSEXP);
    Rcpp::traits::input_parameter< const int >::type thinning(thinningSEXP);
    Rcpp::traits::input_parameter< const int >::type burn(burnSEXP);
    Rcpp::traits::input_parameter< const int >::type nSim(nSimSEXP);
    rcpp_result_gen = Rcpp::wrap(SUN_gibbs_collapsed_sampler_v4(data, X, IDs, STATE, Prior, gPrior, sample, thinning, burn, nSim));
    return rcpp_result_gen;
END_RCPP
}
// SUN_gibbs_collapsed_sampler_v2_Store_Ri_and_delta_v4
Rcpp::List SUN_gibbs_collapsed_sampler_v2_Store_Ri_and_delta_v4(const Rcpp::List data, const arma::mat X, const Rcpp::CharacterVector IDs, Rcpp::List STATE, const Rcpp::List Prior, const Rcpp::List gPrior, const int sample, const int thinning, const int burn, const int nSim);
RcppExport SEXP _BinHEP_SUN_gibbs_collapsed_sampler_v2_Store_Ri_and_delta_v4(SEXP dataSEXP, SEXP XSEXP, SEXP IDsSEXP, SEXP STATESEXP, SEXP PriorSEXP, SEXP gPriorSEXP, SEXP sampleSEXP, SEXP thinningSEXP, SEXP burnSEXP, SEXP nSimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector >::type IDs(IDsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type STATE(STATESEXP);
    Rcpp::traits::input_parameter< const Rcpp::List >::type Prior(PriorSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List >::type gPrior(gPriorSEXP);
    Rcpp::traits::input_parameter< const int >::type sample(sampleSEXP);
    Rcpp::traits::input_parameter< const int >::type thinning(thinningSEXP);
    Rcpp::traits::input_parameter< const int >::type burn(burnSEXP);
    Rcpp::traits::input_parameter< const int >::type nSim(nSimSEXP);
    rcpp_result_gen = Rcpp::wrap(SUN_gibbs_collapsed_sampler_v2_Store_Ri_and_delta_v4(data, X, IDs, STATE, Prior, gPrior, sample, thinning, burn, nSim));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BinHEP_mvrnormArma", (DL_FUNC) &_BinHEP_mvrnormArma, 3},
    {"_BinHEP_mvrnormArma1", (DL_FUNC) &_BinHEP_mvrnormArma1, 2},
    {"_BinHEP_rcpp_qtnorm_vec", (DL_FUNC) &_BinHEP_rcpp_qtnorm_vec, 4},
    {"_BinHEP_rcpp_rtnorm_vec", (DL_FUNC) &_BinHEP_rcpp_rtnorm_vec, 3},
    {"_BinHEP_cpp_rdirichletArma1", (DL_FUNC) &_BinHEP_cpp_rdirichletArma1, 1},
    {"_BinHEP_rcpp_sample", (DL_FUNC) &_BinHEP_rcpp_sample, 3},
    {"_BinHEP_rcpp_rTheta_conditioned_RaoBlackwellAuxSMC", (DL_FUNC) &_BinHEP_rcpp_rTheta_conditioned_RaoBlackwellAuxSMC, 12},
    {"_BinHEP_rcpp_rEta_conditioned_RaoBlackwellAuxSMC", (DL_FUNC) &_BinHEP_rcpp_rEta_conditioned_RaoBlackwellAuxSMC, 12},
    {"_BinHEP_rcpp_get_Ri_wSplit", (DL_FUNC) &_BinHEP_rcpp_get_Ri_wSplit, 3},
    {"_BinHEP_rcpp_get_Ri_wSplit_from_eta", (DL_FUNC) &_BinHEP_rcpp_get_Ri_wSplit_from_eta, 2},
    {"_BinHEP_sample_Ri_under_g_wSplit", (DL_FUNC) &_BinHEP_sample_Ri_under_g_wSplit, 10},
    {"_BinHEP_sample_biniary_ts_wSplit_from_G", (DL_FUNC) &_BinHEP_sample_biniary_ts_wSplit_from_G, 10},
    {"_BinHEP_SUN_gibbs_collapsed_sampler_v2", (DL_FUNC) &_BinHEP_SUN_gibbs_collapsed_sampler_v2, 10},
    {"_BinHEP_SUN_gibbs_collapsed_sampler_v2_Store_Ri_and_delta", (DL_FUNC) &_BinHEP_SUN_gibbs_collapsed_sampler_v2_Store_Ri_and_delta, 10},
    {"_BinHEP_rcpp_get_Ri_wSplit_v3", (DL_FUNC) &_BinHEP_rcpp_get_Ri_wSplit_v3, 3},
    {"_BinHEP_rcpp_get_Ri_wSplit_from_eta_v3", (DL_FUNC) &_BinHEP_rcpp_get_Ri_wSplit_from_eta_v3, 2},
    {"_BinHEP_sample_Ri_under_g_wSplit_v3", (DL_FUNC) &_BinHEP_sample_Ri_under_g_wSplit_v3, 10},
    {"_BinHEP_SUN_gibbs_collapsed_sampler_v3", (DL_FUNC) &_BinHEP_SUN_gibbs_collapsed_sampler_v3, 10},
    {"_BinHEP_SUN_gibbs_collapsed_sampler_v2_Store_Ri_and_delta_v3", (DL_FUNC) &_BinHEP_SUN_gibbs_collapsed_sampler_v2_Store_Ri_and_delta_v3, 10},
    {"_BinHEP_rcpp_get_Ri_wSplit_v4", (DL_FUNC) &_BinHEP_rcpp_get_Ri_wSplit_v4, 3},
    {"_BinHEP_rcpp_get_Ri_wSplit_from_eta_v4", (DL_FUNC) &_BinHEP_rcpp_get_Ri_wSplit_from_eta_v4, 2},
    {"_BinHEP_sample_Ri_under_g_wSplit_v4", (DL_FUNC) &_BinHEP_sample_Ri_under_g_wSplit_v4, 10},
    {"_BinHEP_SUN_gibbs_collapsed_sampler_v4", (DL_FUNC) &_BinHEP_SUN_gibbs_collapsed_sampler_v4, 10},
    {"_BinHEP_SUN_gibbs_collapsed_sampler_v2_Store_Ri_and_delta_v4", (DL_FUNC) &_BinHEP_SUN_gibbs_collapsed_sampler_v2_Store_Ri_and_delta_v4, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_BinHEP(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
