# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Collapsed Gibbs sampler for the SUN-DPM model (full output)
NULL

#' Collapsed Gibbs sampler for the SUN model (lightweight output)
NULL

#' @name mvrnormArma
#' @title Multivariate normal sampler (Cholesky, user-facing)
#'
#' @description
#' Wrappers around the internal Cholesky-based multivariate normal 
#' sampler.  \code{mvrnormArma} returns \eqn{n} samples as an \eqn{n \times p}
#' matrix; \code{mvrnormArma1} returns a single draw as a column vector.
#'
#' The covariance matrix \eqn{\boldsymbol{\Sigma}} must be symmetric and
#' positive definite.  Armadillo's \code{chol()} will throw a runtime error if
#' the matrix is not positive definite.
#'
#' @param n     (\code{mvrnormArma} only) Number of samples to draw.
#' @param mu    Mean vector of length \eqn{p}.
#' @param sigma Symmetric positive-definite covariance matrix (\eqn{p \times p}).
#'
#' @return
#' \describe{
#'   \item{\code{mvrnormArma}}{An \eqn{n \times p} numeric matrix; rows are
#'     independent draws from \eqn{\mathcal{N}_p(\boldsymbol{\mu},
#'     \boldsymbol{\Sigma})}.}
#'   \item{\code{mvrnormArma1}}{A numeric column vector of length \eqn{p}.}
#' }
#'
#' @examples
#' Sigma <- diag(c(1, 2))
#' mu    <- c(0, 0)
#'
#' # Draw 100 samples
#' samp <- mvrnormArma(n = 100, mu = mu, sigma = Sigma)
#' colMeans(samp)          # should be close to mu
#' cov(samp)               # should be close to Sigma
#'
#' # Single draw
#' mvrnormArma1(mu = mu, sigma = Sigma)
#'
#' @seealso \code{\link{cpp_mvrnormArma}}, \code{\link{cpp_mvrnormArma1}},
#'   \code{\link{cpp_mvrnormArma_spectral}}
mvrnormArma <- function(n, mu, sigma) {
    .Call(`_BinHEP_mvrnormArma`, n, mu, sigma)
}

#' @rdname mvrnormArma
mvrnormArma1 <- function(mu, sigma) {
    .Call(`_BinHEP_mvrnormArma1`, mu, sigma)
}

#' Vectorised quantile function of the truncated normal distribution
#'
#' Based on the univariate function of \code{RcppDist}.
#' Evaluates the inverse CDF of the truncated normal
#' distribution element-wise over vectors of probabilities, means, and
#' truncation bounds.  Each element \eqn{i} of the output is
#' \eqn{Q_{\text{TN}}(p_i;\, \mu_i,\, 1,\, a_i,\, b_i)}, i.e. the quantile
#' at probability \eqn{p_i} of a \eqn{\mathcal{N}(\mu_i, 1)} distribution
#' truncated to \eqn{[a_i, b_i]}.
#'
#' Internally delegates to \code{q_truncnorm()} from the \pkg{RcppDist}
#' \code{truncnorm} header, which uses the closed-form expression based on the
#' standard normal CDF.
#'
#' @param p  Vector of probabilities in \eqn{(0, 1)}.
#' @param mu Vector of location parameters (means before truncation).
#' @param a  Vector of lower truncation bounds (\code{-Inf} is allowed).
#' @param b  Vector of upper truncation bounds (\code{Inf} is allowed).
#'
#' @details
#' All input vectors must have the same length.  The standard deviation is
#' fixed at 1; scale \code{mu}, \code{a}, and \code{b} accordingly if a
#' different scale is needed.
#'
#' @return Numeric vector of quantiles of the same length as \code{p}.
#'
#' @seealso \code{\link{rcpp_rtnorm_vec}}
#'
#' @examples
#' # 50th percentile of N(0,1) truncated to [0, Inf)
#' rcpp_qtnorm_vec(p = 0.5, mu = 0, a = 0, b = Inf)
rcpp_qtnorm_vec <- function(p, mu, a, b) {
    .Call(`_BinHEP_rcpp_qtnorm_vec`, p, mu, a, b)
}

#' Vectorised random sampler from the truncated normal distribution
#' 
#' Based on the univariate function of \code{RcppDist}.
#' Draws one independent variate per element from a (possibly distinct)
#' truncated normal distribution.  Each draw \eqn{i} is a realisation of
#' \eqn{\mathcal{N}(\mu_i, 1)} truncated to \eqn{[a_i, b_i]}.
#'
#' Internally delegates to \code{r_truncnorm()} from the \pkg{RcppDist}
#' \code{truncnorm} header.
#'
#' @param mu Vector of location parameters (means before truncation).
#' @param a  Vector of lower truncation bounds (\code{-Inf} is allowed).
#' @param b  Vector of upper truncation bounds (\code{Inf} is allowed).
#'
#' @details
#' The standard deviation is fixed at 1.  All vectors must have the same
#' length.  This function is especially suited to block-updating steps in
#' Gibbs samplers for probit or tobit models, where each latent variable has
#' its own mean and truncation region.
#'
#' @return Numeric vector of random draws of the same length as \code{mu}.
#'
#' @seealso \code{\link{rcpp_qtnorm_vec}}
#'
#' @examples
#' # Draw from N(0,1) truncated to [0, Inf) and N(1,1) truncated to [-1, 1]
#' rcpp_rtnorm_vec(mu = c(0, 1), a = c(0, -1), b = c(Inf, 1))
rcpp_rtnorm_vec <- function(mu, a, b) {
    .Call(`_BinHEP_rcpp_rtnorm_vec`, mu, a, b)
}

#' Draw a single sample from a Dirichlet distribution
#'
#' Generates one draw from \eqn{\text{Dir}(\boldsymbol{\alpha})} using the
#' standard Gamma-ratio method: independently sample
#' \eqn{x_k \sim \text{Gamma}(\alpha_k, 1)} for \eqn{k = 1, \ldots, K} and
#' return \eqn{\mathbf{x} / \sum_k x_k}.
#'
#' @param parameters Concentration parameter vector
#'   \eqn{\boldsymbol{\alpha} = (\alpha_1, \ldots, \alpha_K)^\top} with all
#'   elements strictly positive.
#'
#' @return Numeric vector of length \eqn{K} summing to 1, representing a
#'   probability simplex point.
#'
#' @seealso \code{\link{cpp_rdirichletArma1_plus_1_pos}}
#'
#' @examples
#' # Symmetric Dirichlet with concentration 1 (equivalent to Uniform on simplex)
#' cpp_rdirichletArma1(parameters = c(1, 1, 1))
#'
#' # Informative prior
#' cpp_rdirichletArma1(parameters = c(10, 2, 5))
cpp_rdirichletArma1 <- function(parameters) {
    .Call(`_BinHEP_cpp_rdirichletArma1`, parameters)
}

#' Weighted sampling with replacement from an integer vector
#'
#' Draws \code{size} indices from \code{vec} with replacement, where the
#' probability of drawing element \eqn{i} is proportional to
#' \code{prob[i]}.  Delegates to
#' \code{RcppArmadillo::sample()}, which mirrors R's \code{sample()} but
#' operates directly on \code{arma::uvec} objects, avoiding unnecessary
#' copies.
#'
#' @param vec  Non-negative integer vector of candidates to sample from.
#' @param size Number of draws (positive integer).
#' @param prob Numeric vector of non-negative sampling weights of the same
#'   length as \code{vec}.  Need not sum to 1; normalisation is handled
#'   internally.
#'
#' @return An \code{arma::uvec} (unsigned integer vector) of length
#'   \code{size} containing the sampled elements.
#'
#' @examples
#' candidates <- 0:4
#' weights    <- c(0.1, 0.4, 0.2, 0.2, 0.1)
#' rcpp_sample(vec = candidates, size = 10L, prob = weights)
rcpp_sample <- function(vec, size, prob) {
    .Call(`_BinHEP_rcpp_sample`, vec, size, prob)
}

#' Draw a trajectory from the state-space posterior via a Sequential Monte Carlo sampler 
#'
#' @description
#' Implements an particle filter for a binary, probit-linked Dynamic Model (DLM) with two transition
#' regimes. After the forward pass, a single trajectory
#' \eqn{\{\mathbf{x}_t\}_{t=1}^{T}} is extracted by backward tracing through
#' the stored indices.
#'
#' @param y
#'   Integer vector of length \eqn{T} containing the binary observations
#'   (0 or 1); \code{NA} entries are treated as missing.
#' @param delta
#'   Numeric vector of length \eqn{q} of fixed regression coefficients for
#'   the static covariate \code{x}, defining the scalar offset
#'   \eqn{\mu^* = \mathbf{x}^\top \boldsymbol{\delta}}.
#' @param x
#'   Numeric vector of length \eqn{q} of static covariates entering the probit
#'   mean through \eqn{\mu^*}.
#' @param matFF
#'   \eqn{T \times p} observation design matrix.
#' @param mu0
#'   Numeric vector of length \eqn{p}: prior mean of the initial state
#'   \eqn{\mathbf{x}_0 \sim \mathcal{N}_p(\boldsymbol{\mu}_0,
#'   \boldsymbol{\Sigma}_0)}.
#' @param Sigma0
#'   \eqn{p \times p} symmetric positive-definite prior covariance of the
#'   initial state.
#' @param G
#'   \eqn{p \times p} state transition matrix for the standard regime,
#'   \eqn{\mathbf{x}_t = \mathbf{G}\,\mathbf{x}_{t-1} +
#'   \boldsymbol{\varepsilon}_t}, \eqn{\boldsymbol{\varepsilon}_t \sim
#'   \mathcal{N}_p(\mathbf{0}, \boldsymbol{\Sigma}_\varepsilon)}.
#' @param G_star
#'   \eqn{p \times p} state transition matrix for the alternative regime,
#'   applied at the time points listed in \code{Tstar}.
#' @param SigmaEps
#'   \eqn{p \times p} state evolution covariance for the baseline regime.
#' @param SigmaEps_star
#'   \eqn{p \times p} state evolution covariance for the alternative regime.
#' @param Tstar
#'   Integer vector of time indices at which the alternative regime
#'   transition (\code{G_star}, \code{SigmaEps_star}) is used instead of the
#'   baseline.
#' @param nSim
#'   Number of SMC particles.  Larger values reduce Monte Carlo variance at
#'   the cost of memory and time per step.
#'   Default: \code{500}.
#'
#' @return
#' A \eqn{T \times p} numeric matrix.  Row \eqn{t} contains the state vector
#' \eqn{\mathbf{x}_t} of the single trajectory drawn from
#' \eqn{p(\mathbf{x}_{1:T} \mid y_{1:T})}.
#'
#' @seealso
#' \code{\link{cpp_mvrnormArma_transposed}}, \code{\link{rcpp_rtnorm_vec}},
#' \code{\link{rcpp_sample}}, \code{\link{rcpp_index_gen}}
#'
#' @examples
#' \dontrun{
#' set.seed(14041995)
#' TT  <- 50
#' p   <- 2
#' y   <- rbinom(TT, 1, 0.6)
#' y[sample(TT, 5)] <- NA          # inject some missing observations
#'
#' matFF   <- matrix(c(rep(1, TT), seq_len(TT)), nrow = TT)
#' mu0     <- rep(0, p)
#' Sigma0  <- diag(p)
#' G       <- diag(p) * 0.05
#' G_star  <- diag(p) * 0.80
#' SigE    <- diag(p) * 0.1
#' SigE_s  <- diag(p) * 1
#' delta   <- c(0.1, -0.1)
#' x       <- c(1, 0)
#' Tstar   <- c(10L, 30L)          # regime switches at t = 10 and t = 30
#'
#' traj <- rcpp_rTheta_conditioned_RaoBlackwellAuxSMC(
#'   y          = as.integer(y),
#'   delta      = delta,
#'   x          = x,
#'   matFF      = matFF,
#'   mu0        = mu0,
#'   Sigma0     = Sigma0,
#'   G          = G,
#'   G_star     = G_star,
#'   SigmaEps   = SigE,
#'   SigmaEps_star = SigE_s,
#'   Tstar      = Tstar,
#'   nSim       = 500L
#' )
#' dim(traj)    # TT x p
#' }
#' 
rcpp_rTheta_conditioned_RaoBlackwellAuxSMC <- function(y, delta, x, matFF, mu0, Sigma0, G, G_star, SigmaEps, SigmaEps_star, Tstar, nSim = 500L) {
    .Call(`_BinHEP_rcpp_rTheta_conditioned_RaoBlackwellAuxSMC`, y, delta, x, matFF, mu0, Sigma0, G, G_star, SigmaEps, SigmaEps_star, Tstar, nSim)
}

#' Sample the centered linear predictor trajectory from a Rao-Blackwellised
#' auxiliary SMC
#'
#' @description
#' Runs the full forward auxiliary particle filter and backward trajectory
#' extraction of
#' \code{\link{rcpp_rTheta_conditioned_RaoBlackwellAuxSMC}}, but instead of
#' returning the latent state matrix, it returns the a centered linear predictor as
#' a vector. 
#'
#' @inheritParams rcpp_rTheta_conditioned_RaoBlackwellAuxSMC
#'
#' @return A numeric vector of length \eqn{T}. 
#'
#' @seealso \code{\link{rcpp_rTheta_conditioned_RaoBlackwellAuxSMC}}
#'
#' @examples
#' \dontrun{
#' eta <- rcpp_rCenteredLinearPredictor_RaoBlackwellAuxSMC(
#'   y             = as.integer(y),
#'   delta         = delta,
#'   x             = x_cov,
#'   matFF         = matFF,
#'   mu0           = mu0,
#'   Sigma0        = Sigma0,
#'   G             = G,
#'   G_star        = G_star,
#'   SigmaEps      = SigE,
#'   SigmaEps_star = SigE_s,
#'   Tstar         = Tstar,
#'   nSim          = 500L
#' )
#' length(eta)   # T
#' # Full probit mean at each t: eta + mu_star
#' }
#' 
rcpp_rEta_conditioned_RaoBlackwellAuxSMC <- function(y, delta, x, matFF, mu0, Sigma0, G, G_star, SigmaEps, SigmaEps_star, Tstar, nSim = 500L) {
    .Call(`_BinHEP_rcpp_rEta_conditioned_RaoBlackwellAuxSMC`, y, delta, x, matFF, mu0, Sigma0, G, G_star, SigmaEps, SigmaEps_star, Tstar, nSim)
}

#' Compute the summary statistics \eqn{R_i} from the state trajectory
#'
#' @description
#' Given the full latent state trajectory \eqn{\boldsymbol{\Theta}_i \in
#' \mathbb{R}^{T_i \times p}} and the observation design matrix \eqn{\mathbf{Z}_i
#' \in \mathbb{R}^{T \times p}}, this function returns the integer \eqn{R_i \in \{0, \ldots, 7\}}.
#'
#' For a version that accepts \eqn{\boldsymbol{\eta}} directly (avoiding
#' recomputation), see \code{\link{rcpp_get_Ri_wSplit_from_eta}}.
#'
#' @param theta \eqn{T_i \times p} matrix of latent states
#'   \eqn{\mathbf{x}_1, \ldots, \mathbf{x}_T} (one row per time point).
#' @param Zi \eqn{T \times p} observation design matrix for series \eqn{i}.
#'   Row \eqn{t} is \eqn{\mathbf{F}_t^\top}.
#' @param Tstar Numeric vector of 0-based split-point indices defining the
#'   last segment boundary used by criterion \eqn{R_3}.
#'
#' @return An integer in \eqn{\{0, \ldots, 7\}}.
#'
#' @seealso \code{\link{rcpp_get_Ri_wSplit_from_eta}},
#'   \code{\link{sample_Ri_under_g_wSplit}}
rcpp_get_Ri_wSplit <- function(theta, Zi, Tstar) {
    .Call(`_BinHEP_rcpp_get_Ri_wSplit`, theta, Zi, Tstar)
}

#' Compute \eqn{R_i} directly from the centered linear predictor.
#'
#' @description
#' Identical to \code{\link{rcpp_get_Ri_wSplit}} but accepts the centered
#' linear predictor vector.
#'
#' @param eta  Numeric vector of length \eqn{T}: the centered linear
#'   predictor \eqn{\eta_t = \mathbf{F}_t^\top \mathbf{x}_t}.
#' @param Tstar Numeric vector of 0-based split-point indices; see
#'   \code{\link{rcpp_get_Ri_wSplit}} for details.
#'
#' @return An integer in \eqn{\{0, \ldots, 7\}}.
#'
#' @seealso \code{\link{rcpp_get_Ri_wSplit}},
#'   \code{\link{rcpp_rCenteredLinearPredictor_RaoBlackwellAuxSMC}}
rcpp_get_Ri_wSplit_from_eta <- function(eta, Tstar) {
    .Call(`_BinHEP_rcpp_get_Ri_wSplit_from_eta`, eta, Tstar)
}

#' Sample the prior predictive distribution of \eqn{R_i} under the state-space
#' prior \eqn{g}
#'
#' @description
#' Used to approximates the prior predictive distribution of the \eqn{R_i} by Monte Carlo simulation
#'  under the state-space prior \eqn{g} defined in the manuscript, Section 3.  For each of \code{nSim}
#' draws:
#' \enumerate{
#'   \item a full state trajectory
#'         \eqn{\mathbf{x}_0, \mathbf{x}_1, \ldots, \mathbf{x}_T} is
#'         simulated from the prior;
#'   \item the risk index \eqn{R_i \in \{0, \ldots, 7\}} is computed via
#'         \code{\link{rcpp_get_Ri_wSplit}}.
#' }
#' The returned vector of \code{nSim} draws can be used to estimate
#' \eqn{p(R_i = r \mid g)} for each \eqn{r}, enabling prior elicitation
#' and sensitivity analysis as described in the paper.
#'
#' @param TT    Length of the time series \eqn{T_i}.
#' @param matFF \eqn{T_i \times p} observation design matrix (same role as
#'   \code{Zi} in \code{\link{rcpp_get_Ri_wSplit}}).
#' @param mu0   Prior mean of the initial state.
#' @param Sigma0 Prior covariance of \eqn{\mathbf{x}_0} (\eqn{p \times p}).
#' @param G        Baseline transition matrix (\eqn{p \times p}).
#' @param G_star   Alternative-regime transition matrix (\eqn{p \times p}).
#' @param SigmaEps      Baseline evolution covariance (\eqn{p \times p}).
#' @param SigmaEps_star Alternative evolution covariance
#'   (\eqn{p \times p}).
#' @param Tstar  Numeric vector of \strong{0-based} split-point indices
#'   at which the alternative regime is applied.
#' @param nSim  Number of Monte Carlo draws.  Default: \code{10000}.
#'
#' @return A numeric vector of length \code{nSim} with values in
#'   \eqn{\{0, \ldots, 7\}}, representing independent draws from the prior
#'   predictive distribution of \eqn{R_i} under \eqn{g}.
#'
#' @seealso \code{\link{rcpp_get_Ri_wSplit}},
#'   \code{\link{rcpp_get_Ri_wSplit_from_eta}}
#'
#' @examples
#' \dontrun{
#' draws <- sample_Ri_under_g_wSplit(
#'   TT          = 365L,
#'   matFF       = matFF,
#'   mu0         = rep(0, p),
#'   Sigma0      = diag(p),
#'   G           = G,
#'   G_star      = G_star,
#'   SigmaEps    = SigE,
#'   SigmaEps_star = SigE_s,
#'   Tstar       = c(90, 365),
#'   nSim        = 10000L
#' )
#' }
sample_Ri_under_g_wSplit <- function(TT, matFF, mu0, Sigma0, G, G_star, SigmaEps, SigmaEps_star, Tstar, nSim = 10000L) {
    .Call(`_BinHEP_sample_Ri_under_g_wSplit`, TT, matFF, mu0, Sigma0, G, G_star, SigmaEps, SigmaEps_star, Tstar, nSim)
}

#' Sample from the prior predictive distribution a realization for the state-space parameters.
#'
#' @description
#' Used to approximates the prior predictive distribution of the \eqn{R_i} by Monte Carlo simulation
#'  under the state-space prior \eqn{g} defined in the manuscript, Section 3.  For each of \code{nSim}
#' draws:
#' \enumerate{
#'   \item a full state trajectory
#'         \eqn{\mathbf{x}_0, \mathbf{x}_1, \ldots, \mathbf{x}_T} is
#'         simulated from the prior;
#'   \item the risk index \eqn{R_i \in \{0, \ldots, 7\}} is computed via
#'         \code{\link{rcpp_get_Ri_wSplit}}.
#' }
#' The returned vector of \code{nSim} draws can be used to estimate
#' \eqn{p(R_i = r \mid g)} for each \eqn{r}, enabling prior elicitation
#' and sensitivity analysis as described in the paper.
#'
#' @param TT    Length of the time series \eqn{T_i}.
#' @param matFF \eqn{T_i \times p} observation design matrix (same role as
#'   \code{Zi} in \code{\link{rcpp_get_Ri_wSplit}}).
#' @param mu0   Prior mean of the initial state.
#' @param Sigma0 Prior covariance of \eqn{\mathbf{x}_0} (\eqn{p \times p}).
#' @param G        Baseline transition matrix (\eqn{p \times p}).
#' @param G_star   Alternative-regime transition matrix (\eqn{p \times p}).
#' @param SigmaEps      Baseline evolution covariance (\eqn{p \times p}).
#' @param SigmaEps_star Alternative evolution covariance
#'   (\eqn{p \times p}).
#' @param Tstar  Numeric vector of \strong{0-based} split-point indices
#'   at which the alternative regime is applied.
#' @param nSim  Number of Monte Carlo draws.  Default: \code{10000}.
#'
#' @return A numeric vector of length \code{nSim} with values in
#'   \eqn{\{0, \ldots, 7\}}, representing independent draws from the prior
#'   predictive distribution of \eqn{R_i} under \eqn{g}.
#'
#' @seealso \code{\link{rcpp_get_Ri_wSplit}},
#'   \code{\link{rcpp_get_Ri_wSplit_from_eta}}
#'
#' @examples
#' \dontrun{
#' draws <- sample_Ri_under_g_wSplit(
#'   TT          = 365L,
#'   matFF       = matFF,
#'   mu0         = rep(0, p),
#'   Sigma0      = diag(p),
#'   G           = G,
#'   G_star      = G_star,
#'   SigmaEps    = SigE,
#'   SigmaEps_star = SigE_s,
#'   Tstar       = c(90, 365),
#'   nSim        = 10000L
#' )
#' }
sample_biniary_ts_wSplit_from_G <- function(mu, TT, matFF, mu0, Sigma0, G, G_star, SigmaEps, SigmaEps_star, Tstar) {
    .Call(`_BinHEP_sample_biniary_ts_wSplit_from_G`, mu, TT, matFF, mu0, Sigma0, G, G_star, SigmaEps, SigmaEps_star, Tstar)
}

#' Collapsed Gibbs sampler for the BNP mxiture of SUN models (full output)
#'
#' @description
#' Runs a collapsed Gibbs sampler for the model described in the paper. 
#'
#' For a memory-efficient variant that stores only
#' \eqn{(\boldsymbol{\delta}, \mathbf{R})} see
#' \code{\link{SUN_gibbs_collapsed_sampler_v2_Store_Ri_and_delta}}.
#'
#' @param data
#'   Named \code{Rcpp::List} of length \eqn{n}.  Each element is itself a
#'   list with at least a field \code{"ts"} (the binary time series for
#'   subject \eqn{i}) and any covariates needed by the update functions.
#' @param X
#'   \eqn{n \times q} matrix of subject-level static covariates
#'   \eqn{\mathbf{x}_i}.  Used to build the stacked probit design matrix
#'   and forwarded to the state-trajectory update.
#' @param IDs
#'   Character vector of length \eqn{n} with subject identifiers.
#' @param STATE
#'   Named \code{Rcpp::List} holding the current MCMC state.  Must contain
#'   at least the fields \code{"rho"}, \code{"delta"}, \code{"xi"},
#'   \code{"Gamma"}, and \code{"Ri"}.  Modified in place at each sweep.
#' @param Prior
#'   Named list of hyperparameters for the DP and probit blocks:
#'   \describe{
#'     \item{\code{"a"}}{Concentration vector \eqn{\mathbf{a}} of the
#'       base-measure Dirichlet prior on \eqn{\boldsymbol{\xi}^*}.}
#'     \item{\code{"M"}}{DP precision parameter \eqn{M > 0}.}
#'     \item{\code{"sigma"}}{Discount parameter \eqn{\sigma}.}
#'     \item{\code{"d0"}}{Prior mean vector for \eqn{\boldsymbol{\delta}}.}
#'     \item{\code{"D0"}}{Diagonal of the prior precision matrix
#'       \eqn{\mathbf{D}_0} for \eqn{\boldsymbol{\delta}}.}
#'   }
#' @param gPrior
#'   Named list of state-space prior hyperparameters for the DLM prior
#'   \eqn{g}:
#'   \describe{
#'     \item{\code{"m0"}, \code{"S0"}}{Prior mean and covariance of the
#'       initial state \eqn{\mathbf{x}_0}.}
#'     \item{\code{"G1"}, \code{"G2"}}{Baseline and alternative-regime
#'       transition matrices \eqn{\mathbf{G}} and \eqn{\mathbf{G}^*}.}
#'     \item{\code{"Ve"}, \code{"Ves"}}{Baseline and alternative-regime
#'       innovation covariances
#'       \eqn{\boldsymbol{\Sigma}_\varepsilon} and
#'       \eqn{\boldsymbol{\Sigma}_\varepsilon^*}.}
#'     \item{\code{"gli"}}{\eqn{8 \times K} matrix mapping each risk
#'       category \eqn{R_i \in \{0,\ldots,7\}} to a cluster probability
#'       vector.}
#'   }
#' @param sample    Number of posterior draws to store.
#'   Default: \code{2000}.
#' @param thinning  Store one sample every \code{thinning} post-burn-in.
#'   Default: \code{10}.
#' @param burn      Number of burn-in.
#'   Default: \code{1000}.
#' @param nSim      Number of SMC particles forwarded to the trajectory
#'   sampler inside \code{rcpp_update_Ri_gamma_and_rho}.
#'   Default: \code{100}.
#'
#' @return A named \code{Rcpp::List} with five fields, each of length
#'   \code{sample}:
#'   \describe{
#'     \item{\code{delta}}{\eqn{\texttt{sample} \times q} matrix of draws
#'       of the probit coefficient vector \eqn{\boldsymbol{\delta}}.}
#'     \item{\code{rho}}{\eqn{\texttt{sample} \times n} matrix of cluster
#'       assignment draws \eqn{\boldsymbol{\rho}}.}
#'     \item{\code{xi_star}}{List of \code{sample} draws of the cluster
#'       atom matrix \eqn{\boldsymbol{\xi}^*}.}
#'     \item{\code{Gamma}}{List of \code{sample} draws of the latent state
#'       trajectories \eqn{\boldsymbol{\Gamma}}.}
#'     \item{\code{Ri}}{List of \code{sample} draws of the risk index
#'       vector \eqn{\mathbf{R} = (R_1, \ldots, R_n)}.}
#'   }
#'
#' @seealso
#'   \code{\link{SUN_gibbs_collapsed_sampler_v2_Store_Ri_and_delta}},
#'   \code{\link{rcpp_get_Ri_wSplit}},
#'   \code{\link{rcpp_rCenteredLinearPredictor_RaoBlackwellAuxSMC}}
#'
#' @examples
#' \dontrun{
#' fit <- SUN_gibbs_collapsed_sampler_v2(
#'   data     = subject_list,
#'   X        = X_mat,
#'   IDs      = ids,
#'   STATE    = initial_state,
#'   Prior    = prior_list,
#'   gPrior   = g_prior_list,
#'   sample   = 2000L,
#'   thinning = 10L,
#'   burn     = 1000L,
#'   nSim     = 100L
#' )
SUN_gibbs_collapsed_sampler_v2 <- function(data, X, IDs, STATE, Prior, gPrior, sample = 2000L, thinning = 10L, burn = 1000L, nSim = 100L) {
    .Call(`_BinHEP_SUN_gibbs_collapsed_sampler_v2`, data, X, IDs, STATE, Prior, gPrior, sample, thinning, burn, nSim)
}

#' Collapsed Gibbs sampler for the SUN model (lightweight output)
#'
#' @description
#' Memory-efficient variant of
#' \code{\link{SUN_gibbs_collapsed_sampler_v2}}.  
#'
#' Use this variant when:
#' \itemize{
#'   \item only posterior inference on \eqn{\boldsymbol{\delta}} and the
#'     summaries statistics classification \eqn{p(R_i = r \mid \mathbf{y})} is needed;
#'   \item the number of subjects \eqn{n} or series length \eqn{T} makes
#'     storing full trajectories prohibitive.
#' }
#'
#' All parameters are identical to
#' \code{\link{SUN_gibbs_collapsed_sampler_v2}}; see that page for full
#' descriptions.
#'
#' @inheritParams SUN_gibbs_collapsed_sampler_v2
#'
#' @return A named \code{Rcpp::List} with two fields:
#'   \describe{
#'     \item{\code{delta}}{\eqn{\texttt{sample} \times q} matrix of draws
#'       of \eqn{\boldsymbol{\delta}}.}
#'     \item{\code{Ri}}{List of \code{sample} draws of the risk index
#'       vector \eqn{\mathbf{R} = (R_1, \ldots, R_n)}.}
#'   }
#'
#' @seealso \code{\link{SUN_gibbs_collapsed_sampler_v2}}
#'
#' @examples
#' \dontrun{
#' }
SUN_gibbs_collapsed_sampler_v2_Store_Ri_and_delta <- function(data, X, IDs, STATE, Prior, gPrior, sample = 2000L, thinning = 10L, burn = 1000L, nSim = 100L) {
    .Call(`_BinHEP_SUN_gibbs_collapsed_sampler_v2_Store_Ri_and_delta`, data, X, IDs, STATE, Prior, gPrior, sample, thinning, burn, nSim)
}

rcpp_get_Ri_wSplit_v3 <- function(theta, Zi, Tstar) {
    .Call(`_BinHEP_rcpp_get_Ri_wSplit_v3`, theta, Zi, Tstar)
}

rcpp_get_Ri_wSplit_from_eta_v3 <- function(eta, Tstar) {
    .Call(`_BinHEP_rcpp_get_Ri_wSplit_from_eta_v3`, eta, Tstar)
}

sample_Ri_under_g_wSplit_v3 <- function(TT, matFF, mu0, Sigma0, G, G_star, SigmaEps, SigmaEps_star, Tstar, nSim = 10000L) {
    .Call(`_BinHEP_sample_Ri_under_g_wSplit_v3`, TT, matFF, mu0, Sigma0, G, G_star, SigmaEps, SigmaEps_star, Tstar, nSim)
}

#' Collapsed Gibbs sampler for the SUN-DPM model (full output)
#'
#' @description
#' Runs a collapsed Gibbs sampler for the model described in the paper. 
#'
#' For a memory-efficient variant that stores only
#' \eqn{(\boldsymbol{\delta}, \mathbf{R})} see
#' \code{\link{SUN_gibbs_collapsed_sampler_v2_Store_Ri_and_delta}}.
#'
#' @param data
#'   Named \code{Rcpp::List} of length \eqn{n}.  Each element is itself a
#'   list with at least a field \code{"ts"} (the binary time series for
#'   subject \eqn{i}) and any covariates needed by the update functions.
#' @param X
#'   \eqn{n \times q} matrix of subject-level static covariates
#'   \eqn{\mathbf{x}_i}.  Used to build the stacked probit design matrix
#'   and forwarded to the state-trajectory update.
#' @param IDs
#'   Character vector of length \eqn{n} with subject identifiers.
#' @param STATE
#'   Named \code{Rcpp::List} holding the current MCMC state.  Must contain
#'   at least the fields \code{"rho"}, \code{"delta"}, \code{"xi"},
#'   \code{"Gamma"}, and \code{"Ri"}.  Modified in place at each sweep.
#' @param Prior
#'   Named list of hyperparameters for the DP and probit blocks:
#'   \describe{
#'     \item{\code{"a"}}{Concentration vector \eqn{\mathbf{a}} of the
#'       base-measure Dirichlet prior on \eqn{\boldsymbol{\xi}^*}.}
#'     \item{\code{"M"}}{DP precision parameter \eqn{M > 0}.}
#'     \item{\code{"sigma"}}{Discount parameter \eqn{\sigma}.}
#'     \item{\code{"d0"}}{Prior mean vector for \eqn{\boldsymbol{\delta}}.}
#'     \item{\code{"D0"}}{Diagonal of the prior precision matrix
#'       \eqn{\mathbf{D}_0} for \eqn{\boldsymbol{\delta}}.}
#'   }
#' @param gPrior
#'   Named list of state-space prior hyperparameters for the DLM prior
#'   \eqn{g}:
#'   \describe{
#'     \item{\code{"m0"}, \code{"S0"}}{Prior mean and covariance of the
#'       initial state \eqn{\mathbf{x}_0}.}
#'     \item{\code{"G1"}, \code{"G2"}}{Baseline and alternative-regime
#'       transition matrices \eqn{\mathbf{G}} and \eqn{\mathbf{G}^*}.}
#'     \item{\code{"Ve"}, \code{"Ves"}}{Baseline and alternative-regime
#'       innovation covariances
#'       \eqn{\boldsymbol{\Sigma}_\varepsilon} and
#'       \eqn{\boldsymbol{\Sigma}_\varepsilon^*}.}
#'     \item{\code{"gli"}}{\eqn{8 \times K} matrix mapping each risk
#'       category \eqn{R_i \in \{0,\ldots,7\}} to a cluster probability
#'       vector.}
#'   }
#' @param sample    Number of posterior draws to store.
#'   Default: \code{2000}.
#' @param thinning  Store one sample every \code{thinning} post-burn-in.
#'   Default: \code{10}.
#' @param burn      Number of burn-in.
#'   Default: \code{1000}.
#' @param nSim      Number of SMC particles forwarded to the trajectory
#'   sampler inside \code{rcpp_update_Ri_gamma_and_rho}.
#'   Default: \code{100}.
#'
#' @return A named \code{Rcpp::List} with five fields, each of length
#'   \code{sample}:
#'   \describe{
#'     \item{\code{delta}}{\eqn{\texttt{sample} \times q} matrix of draws
#'       of the probit coefficient vector \eqn{\boldsymbol{\delta}}.}
#'     \item{\code{rho}}{\eqn{\texttt{sample} \times n} matrix of cluster
#'       assignment draws \eqn{\boldsymbol{\rho}}.}
#'     \item{\code{xi_star}}{List of \code{sample} draws of the cluster
#'       atom matrix \eqn{\boldsymbol{\xi}^*}.}
#'     \item{\code{Gamma}}{List of \code{sample} draws of the latent state
#'       trajectories \eqn{\boldsymbol{\Gamma}}.}
#'     \item{\code{Ri}}{List of \code{sample} draws of the risk index
#'       vector \eqn{\mathbf{R} = (R_1, \ldots, R_n)}.}
#'   }
#'
#' @seealso
#'   \code{\link{SUN_gibbs_collapsed_sampler_v2_Store_Ri_and_delta}},
#'   \code{\link{rcpp_get_Ri_wSplit}},
#'   \code{\link{rcpp_rCenteredLinearPredictor_RaoBlackwellAuxSMC}}
#'
#' @examples
#' \dontrun{
#' fit <- SUN_gibbs_collapsed_sampler_v2(
#'   data     = subject_list,
#'   X        = X_mat,
#'   IDs      = ids,
#'   STATE    = initial_state,
#'   Prior    = prior_list,
#'   gPrior   = g_prior_list,
#'   sample   = 2000L,
#'   thinning = 10L,
#'   burn     = 1000L,
#'   nSim     = 100L
#' )
SUN_gibbs_collapsed_sampler_v3 <- function(data, X, IDs, STATE, Prior, gPrior, sample = 2000L, thinning = 10L, burn = 1000L, nSim = 100L) {
    .Call(`_BinHEP_SUN_gibbs_collapsed_sampler_v3`, data, X, IDs, STATE, Prior, gPrior, sample, thinning, burn, nSim)
}

#' Collapsed Gibbs sampler for the SUN model (lightweight output)
#'
#' @description
#' Memory-efficient variant of
#' \code{\link{SUN_gibbs_collapsed_sampler_v2}}.  
#'
#' Use this variant when:
#' \itemize{
#'   \item only posterior inference on \eqn{\boldsymbol{\delta}} and the
#'     summaries statistics classification \eqn{p(R_i = r \mid \mathbf{y})} is needed;
#'   \item the number of subjects \eqn{n} or series length \eqn{T} makes
#'     storing full trajectories prohibitive.
#' }
#'
#' All parameters are identical to
#' \code{\link{SUN_gibbs_collapsed_sampler_v2}}; see that page for full
#' descriptions.
#'
#' @inheritParams SUN_gibbs_collapsed_sampler_v2
#'
#' @return A named \code{Rcpp::List} with two fields:
#'   \describe{
#'     \item{\code{delta}}{\eqn{\texttt{sample} \times q} matrix of draws
#'       of \eqn{\boldsymbol{\delta}}.}
#'     \item{\code{Ri}}{List of \code{sample} draws of the risk index
#'       vector \eqn{\mathbf{R} = (R_1, \ldots, R_n)}.}
#'   }
#'
#' @seealso \code{\link{SUN_gibbs_collapsed_sampler_v2}}
#'
#' @examples
#' \dontrun{
#' }
SUN_gibbs_collapsed_sampler_v2_Store_Ri_and_delta_v3 <- function(data, X, IDs, STATE, Prior, gPrior, sample = 2000L, thinning = 10L, burn = 1000L, nSim = 100L) {
    .Call(`_BinHEP_SUN_gibbs_collapsed_sampler_v2_Store_Ri_and_delta_v3`, data, X, IDs, STATE, Prior, gPrior, sample, thinning, burn, nSim)
}

rcpp_get_Ri_wSplit_v4 <- function(theta, Zi, Tstar) {
    .Call(`_BinHEP_rcpp_get_Ri_wSplit_v4`, theta, Zi, Tstar)
}

rcpp_get_Ri_wSplit_from_eta_v4 <- function(eta, Tstar) {
    .Call(`_BinHEP_rcpp_get_Ri_wSplit_from_eta_v4`, eta, Tstar)
}

sample_Ri_under_g_wSplit_v4 <- function(TT, matFF, mu0, Sigma0, G, G_star, SigmaEps, SigmaEps_star, Tstar, nSim = 10000L) {
    .Call(`_BinHEP_sample_Ri_under_g_wSplit_v4`, TT, matFF, mu0, Sigma0, G, G_star, SigmaEps, SigmaEps_star, Tstar, nSim)
}

SUN_gibbs_collapsed_sampler_v4 <- function(data, X, IDs, STATE, Prior, gPrior, sample = 2000L, thinning = 10L, burn = 1000L, nSim = 100L) {
    .Call(`_BinHEP_SUN_gibbs_collapsed_sampler_v4`, data, X, IDs, STATE, Prior, gPrior, sample, thinning, burn, nSim)
}

SUN_gibbs_collapsed_sampler_v2_Store_Ri_and_delta_v4 <- function(data, X, IDs, STATE, Prior, gPrior, sample = 2000L, thinning = 10L, burn = 1000L, nSim = 100L) {
    .Call(`_BinHEP_SUN_gibbs_collapsed_sampler_v2_Store_Ri_and_delta_v4`, data, X, IDs, STATE, Prior, gPrior, sample, thinning, burn, nSim)
}

